# Generated by Django 4.2.10 on 2024-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0037_searchmodelconfig_bi_encoder_docs_encode_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="texttoimagemodelconfig",
            name="api_key",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="texttoimagemodelconfig",
            name="model_type",
            field=models.CharField(
                choices=[("openai", "Openai"), ("stability-ai", "Stabilityai")], default="openai", max_length=200
            ),
        ),
    ]
